### ISSUE TITLE
Not starting by default

### ISSUE THREAD

**Issue by chevdor** [cheperuiz/docker-evcxr#2]
Hello,

I was happy to find your project, this is a great idea.
I fear things may have changed on the jupyter side and/or your readme is outdate.

`docker run --rm -p 8888:8888 cheperuiz/evcxr` end up with:
```
[C 09:37:29.476 NotebookApp] Bad config encountered during initialization:
[C 09:37:29.476 NotebookApp] No such notebook dir: ''/notebooks''
The Jupyter HTML Notebook.

This launches a Tornado based HTML Notebook Server that serves up an
HTML5/Javascript Notebook client.

Subcommands
-----------

Subcommands are launched as `jupyter-notebook cmd [args]`. For information on
using subcommand 'cmd', do: `jupyter-notebook cmd -h`.
...
```

Using `docker run --rm -p 8888:8888 cheperuiz/evcxr jupyter notebook`returns:
```
[I 09:38:43.051 NotebookApp] Writing notebook server cookie secret to /home/rust/.local/share/jupyter/runtime/notebook_cookie_secret
Traceback (most recent call last):
  File "/usr/bin/jupyter-notebook", line 11, in <module>
    load_entry_point('notebook==5.7.8', 'console_scripts', 'jupyter-notebook')()
  File "/usr/lib/python3/dist-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/lib/python3/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/usr/lib/python3/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/notebook/notebookapp.py", line 1630, in initialize
    self.init_webapp()
  File "/usr/lib/python3/dist-packages/notebook/notebookapp.py", line 1407, in init_webapp
    self.http_server.listen(port, self.ip)
  File "/usr/lib/python3/dist-packages/tornado/tcpserver.py", line 143, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/lib/python3/dist-packages/tornado/netutil.py", line 168, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 99] Cannot assign requested address
```

**Comment by cheperuiz** [comment]
Sorry, It's been a while since I created this repo and I haven't done any maintenance in a while... if I have time soon I'll take a look and try to fix/update....

**Comment by chevdor** [comment]
No worries. I initially planned on pushing a PR but ended up making quite some changes so I don't know if you want the full package. If you do, let me know and let's see if we can sync. I created a working version with a few goodies at https://gitlab.com/chevdor/jupyter-rust

**Comment by chevdor** [comment]
Closing this stall issue but you can find the changes at the link above.
Feel free to ping me if you revive the topic.
